version: '2'
services:
  pim-app:
    image: pim
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://pim-mssql:1433;database=pim
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pim-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pim-elasticsearch:9200
    ports:
      - 8080:8080
  pim-mssql:
    extends:
      file: mssql.yml
      service: pim-mssql
  pim-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pim-elasticsearch
